compressor presence check
paolochiodi/htmlcompressor pull request #39
Opened 2017-12-16 13:39 UTC by GeorgeGorbanev

I want to split exceptions: when compressor options not given and when it is not found.

So I added more friendly exception for case, when ` #get_javascript_compressor` or ` #get_css_compressor` not found compressor for given symbol.

Thank you for your job.

2017-12-17 15:23 UTC, paolochiodi requested changes
Hi,
first and foremost thank you for taking the time to submit this PR. I think this is an intelligent change that will help users in debugging any problem they should encounter.

Code wise, I'd like to propose a change. Reusing the `given_option` is a bit confusing and may lead to a misleading error message if `javascript_compressor` is a symbol and `css_compressor` is nil.

I'd suggest to either just use `@options[:javascript_compressor]` to decide which error to raise of have a first check for nil in the first "if"

2017-12-17 22:15 UTC, GeorgeGorbanev commented
I agree, it is much better. Amend it.

Glad to see so fast feedback. Wish this gem will not stop growing.

2017-12-20 21:18 UTC, paolochiodi approved these changes

2017-12-20 21:18 UTC, paolochiodi commented
Thanks for the good work. I've merged, during the festivities I'll have some time to dedicate to this gem and will publish a new version.

2017-12-28 15:31 UTC, merged

2017-12-28 16:41 UTC, paolochiodi commented
@GeorgeGorbanev Published as versions 0.4.0